# =============================================================================
# Tool:        reach.hydro — ReFH2 rainfall-runoff model
# Description: Implements the Revitalised Flood Hydrograph (ReFH2) method
#              (Kjeldsen et al. 2008; Wallingford HydroSolutions 2016).
#
#              ReFH2 comprises three components:
#                1. Loss model: Probability-distributed soil moisture model
#                   (PDM-style) to separate rainfall into runoff and
#                   infiltration. Initial conditions set by seasonal Cini.
#                2. Routing model: Two linear reservoirs (fast/slow) in
#                   parallel, equivalent to a two-component unit hydrograph.
#                3. Baseflow model: Linear reservoir with Baseflow Lag (BL).
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING — UNVERIFIED REGRESSION COEFFICIENTS
#
# The regression equations in refh2_params() were generated by an AI model
# and have NOT been verified against the authoritative source documents.
# The coefficients may be incorrect, partially fabricated, or derived from
# a superseded version of the method.
#
# THE FULL ReFH2 PARAMETER EQUATIONS ARE PROPRIETARY. The complete and
# current regression equations are contained in:
#   Wallingford HydroSolutions (2016). ReFH 2 Technical Guidance.
# This document is not freely available. A licence may be required.
#
# DO NOT USE refh2_params() FOR REAL FLOOD ESTIMATION until every
# coefficient has been checked against a source your team can cite and
# is legally permitted to use. The model structure in refh2_run() is
# believed to be correct but should also be independently verified.
#
# Action required:
#   1. Obtain the Kjeldsen (2007) CEH Technical Note (freely available)
#      and verify which equations and coefficients are published there.
#   2. Contact Wallingford HydroSolutions for the full ReFH2 equations
#      if the team requires the complete licensed method.
#   3. Replace the coefficients in refh2_params() with verified values
#      and remove this warning block.
#   4. Update the GitHub issue (raise one if not already open) to track
#      resolution.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# Flode Module: reach.hydro
# Author:      Forecasting and Warning Team
# Created:     2026-02-23
# Modified:    2026-02-23 - JP: initial implementation; coefficients unverified
# Tier:        2
# Inputs:      Design storm hyetograph (from feh_design_storm()); catchment
#              descriptors; or directly supplied ReFH2 parameters
# Outputs:     Design hydrograph [data.table]; peak flow; flood volume
# Dependencies: data.table
# References:
#   Kjeldsen, T.R. (2007). The revitalised FSR/FEH rainfall-runoff method.
#     Flood Studies Report Technical Note No. 1. CEH. [FREELY AVAILABLE]
#   Wallingford HydroSolutions (2016). ReFH 2 Technical Guidance.
#     [PROPRIETARY — verify licence before use]
# =============================================================================

# =============================================================================
# SECTION 1 : CATCHMENT DESCRIPTOR → PARAMETER REGRESSION
# =============================================================================

#' Estimate ReFH2 parameters from FEH catchment descriptors
#'
#' Applies regression equations to derive ReFH2 model parameters from standard
#' FEH catchment descriptors.
#'
#' @section WARNING — unverified coefficients:
#' The regression coefficients in this function were generated by an AI model
#' and have **not** been verified against the authoritative source documents.
#' The full ReFH2 parameter equations are proprietary (Wallingford
#' HydroSolutions 2016) and may require a licence. **Do not use this function
#' for real flood estimation** until the coefficients have been checked and
#' replaced with verified values. See the file header in `feh_refh2.R` for
#' the full action list.
#'
#' @param area      Catchment area \[km²\]. (AREA)
#' @param bfihost   Baseflow index from HOST soils \[0-1\]. (BFIHOST)
#' @param saar      Standard average annual rainfall \[mm\]. (SAAR)
#' @param farl      Index of flood attenuation by reservoirs and lakes \[0-1\].
#'                  (FARL; default 1.0 = no attenuation)
#' @param urbext    Fraction of catchment urbanised (FEH URBEXT2000).
#'                  Default 0.0 = rural.
#' @param season    `"summer"` (default) or `"winter"`. Affects Cini.
#'
#' @return A list of class `"ReFH2Params"` containing:
#'   \describe{
#'     \item{Cmax}{Maximum soil moisture capacity \[mm\].}
#'     \item{Cini}{Initial soil moisture content \[mm\] (seasonal).}
#'     \item{alpha}{BRC — proportion of runoff going to fast store.}
#'     \item{Tp}{Time-to-peak of unit hydrograph \[hours\].}
#'     \item{BL}{Baseflow lag \[hours\].}
#'     \item{BR}{Baseflow recharge parameter \[—\].}
#'     \item{Kb}{Baseflow recession constant \[—\].}
#'   }
#'
#' @examples
#' p <- refh2_params(area = 250, bfihost = 0.45, saar = 850, farl = 0.98)
#' p
#'
#' @seealso [refh2_run()]
#' @export
refh2_params <- function(area,
                         bfihost,
                         saar,
                         farl   = 1.0,
                         urbext = 0.0,
                         season = "summer") {

  checkmate::assert_number(area,    lower = 0)
  checkmate::assert_number(bfihost, lower = 0, upper = 1)
  checkmate::assert_number(saar,    lower = 0)
  checkmate::assert_number(farl,    lower = 0, upper = 1)
  checkmate::assert_number(urbext,  lower = 0, upper = 1)
  season <- match.arg(season, c("summer", "winter"))

  warning(
    "refh2_params(): regression coefficients are UNVERIFIED and may be ",
    "incorrect or proprietary. Do not use for real flood estimation. ",
    "See ?refh2_params and the feh_refh2.R file header for details.",
    call. = FALSE
  )

  # !! UNVERIFIED — check all coefficients below against Kjeldsen (2007)
  # !! and Wallingford HydroSolutions (2016) before operational use.
  # Urbanisation adjustment to BFIHOST (Kjeldsen 2007, eq 15)
  bfi_adj <- bfihost * (1 - 0.496 * urbext^0.376)

  # Cmax: maximum soil moisture capacity [mm] (Kjeldsen 2007, Table 5)
  Cmax <- exp(3.2397 + 0.6099 * log(1 + saar) -
              0.9926 * log(1 + bfi_adj))

  # Cini: initial condition (fraction of Cmax) — seasonal (Table 5)
  frac_ini <- if (season == "summer") {
    exp(-0.0050 * saar) * (1 - bfi_adj)^0.4
  } else {
    0.5 * exp(-0.0050 * saar) * (1 - bfi_adj)^0.4
  }
  Cini <- Cmax * pmin(frac_ini, 0.99)

  # Tp: time-to-peak [hours] (Kjeldsen 2007, Table 6)
  Tp <- exp(-1.6090 + 0.8294 * log(area) -
            0.4271 * log(1 + saar) + 0.3015 * log(1 + bfi_adj) +
            0.0709 * log(farl))

  # alpha: baseflow recharge coefficient (BRC) (Table 6)
  alpha <- pmin(pmax(
    0.9 * bfi_adj^1.3,
    0), 0.99)

  # BL: baseflow lag [hours] (Table 7)
  BL <- exp(0.4598 + 0.7533 * log(area) -
            0.3004 * log(1 + saar))

  # BR: baseflow recharge (Table 7)
  BR <- exp(-1.6935 + 0.4999 * log(area) + 0.2745 * log(1 + saar))

  # Kb: baseflow recession (Table 7) — empirical
  Kb <- 0.5 * (1 + bfi_adj)

  structure(
    list(Cmax = Cmax, Cini = Cini, alpha = alpha,
         Tp = Tp, BL = BL, BR = BR, Kb = Kb,
         area = area, bfihost = bfihost, saar = saar,
         farl = farl, urbext = urbext, season = season),
    class = "ReFH2Params"
  )
}

#' @export
print.ReFH2Params <- function(x, ...) {
  cat(sprintf("<ReFH2Params> area=%.1f km\u00b2 | BFIHOST=%.3f | SAAR=%d mm | %s\n",
              x$area, x$bfihost, round(x$saar), x$season))
  cat(sprintf("  Cmax=%.1f mm | Cini=%.1f mm | alpha=%.3f\n",
              x$Cmax, x$Cini, x$alpha))
  cat(sprintf("  Tp=%.2f hr | BL=%.2f hr | BR=%.3f | Kb=%.3f\n",
              x$Tp, x$BL, x$BR, x$Kb))
  invisible(x)
}

# =============================================================================
# SECTION 2 : ReFH2 MODEL RUN
# =============================================================================

#' Run the ReFH2 rainfall-runoff model
#'
#' Given a design storm hyetograph and ReFH2 parameters, simulates the direct
#' runoff hydrograph, baseflow, and total flow. The loss model uses a simple
#' probability-distributed soil moisture accounting, and the routing uses
#' two linear reservoirs in series with a time-to-peak unit hydrograph.
#'
#' @param storm    A `data.table` from [feh_design_storm()] with columns
#'                 `time_min` and `rainfall_mm`. Or any `data.table` with
#'                 those columns and a consistent timestep.
#' @param params   A `ReFH2Params` object from [refh2_params()], or a named
#'                 list with the same fields.
#' @param baseflow_0 Initial baseflow \[m³/s\] (scaled by area). Default 0.
#'
#' @return A `data.table` with columns:
#'   \describe{
#'     \item{time_min, time_hr}{Time axes.}
#'     \item{rainfall_mm}{Input rainfall (per timestep).}
#'     \item{loss_mm}{Infiltration loss (per timestep).}
#'     \item{net_rain_mm}{Net (effective) rainfall = rainfall - loss.}
#'     \item{C}{Soil moisture state \[mm\].}
#'     \item{Qd_mm}{Direct runoff depth per timestep \[mm\].}
#'     \item{Qb_mm}{Baseflow depth per timestep \[mm\].}
#'     \item{Q_mm}{Total flow depth per timestep \[mm\].}
#'   }
#'   Attributes: `params`, `peak_flow_mm`, `flood_volume_mm`.
#'
#' @seealso [refh2_params()], [feh_design_storm()]
#' @export
refh2_run <- function(storm, params, baseflow_0 = 0) {

  if (!inherits(params, "ReFH2Params"))
    params <- structure(params, class = "ReFH2Params")

  if (!data.table::is.data.table(storm))
    storm <- data.table::as.data.table(storm)

  req <- c("time_min", "rainfall_mm")
  missing_cols <- setdiff(req, names(storm))
  if (length(missing_cols) > 0)
    stop(sprintf("refh2_run: storm missing columns: %s",
                 paste(missing_cols, collapse = ", ")), call. = FALSE)

  n   <- nrow(storm)
  dt_hr <- diff(storm$time_min[1:2]) / 60  # timestep in hours

  # ---- Pre-allocate output --------------------------------------------------
  out <- data.table::copy(storm)
  out[, c("loss_mm", "net_rain_mm", "C",
          "Qd_mm", "Qb_mm", "Q_mm") := NA_real_]
  out[, time_hr := time_min / 60]

  # ---- Routing kernel: triangular UH → two cascaded linear reservoirs ------
  # Tp in timesteps
  Tp_steps <- max(1L, round(params$Tp / dt_hr))
  uh       <- .refh2_uh(Tp_steps, n)

  # ---- Loss model state -----------------------------------------------------
  C    <- params$Cini  # current soil moisture [mm]
  Cmax <- params$Cmax

  net_rain <- numeric(n)

  for (t in seq_len(n)) {
    P <- max(0, storm$rainfall_mm[t])

    # Simple proportional loss: infiltration = P * (1 - C/Cmax)
    if (Cmax > 0) {
      f_sat   <- C / Cmax
      net_t   <- P * f_sat
      loss_t  <- P - net_t
      C       <- min(C + loss_t, Cmax)
    } else {
      net_t   <- P
      loss_t  <- 0
    }

    out[t, loss_mm    := loss_t]
    out[t, net_rain_mm := net_t]
    out[t, C          := C]
    net_rain[t] <- net_t
  }

  # ---- Route net rain through UH (convolution) ------------------------------
  Qd <- stats::filter(net_rain, uh, sides = 1)
  Qd[is.na(Qd)] <- 0

  # ---- Baseflow: linear recession with recharge from net rain ---------------
  Qb    <- numeric(n)
  Kb    <- params$Kb
  BR    <- params$BR
  bl_steps <- max(1L, round(params$BL / dt_hr))

  Qb_cur <- baseflow_0
  for (t in seq_len(n)) {
    # Lagged recharge
    t_lag   <- max(1L, t - bl_steps)
    recharge <- BR * net_rain[t_lag] * dt_hr
    Qb_cur  <- Qb_cur * Kb + recharge
    Qb[t]   <- Qb_cur
  }

  # ---- Combine --------------------------------------------------------------
  out[, Qd_mm := pmax(0, Qd)]
  out[, Qb_mm := pmax(0, Qb)]
  out[, Q_mm  := Qd_mm + Qb_mm]

  attr(out, "params")          <- params
  attr(out, "peak_flow_mm")    <- max(out$Q_mm)
  attr(out, "flood_volume_mm") <- sum(out$Q_mm) * dt_hr  # mm·hr (depth × time)

  out
}

# Internal: triangular unit hydrograph kernel normalised to unit volume
# Tp_steps: time-to-peak in timesteps; n: total length
.refh2_uh <- function(Tp_steps, n) {
  t_seq <- seq_len(n)
  uh    <- ifelse(t_seq <= Tp_steps,
                  t_seq / Tp_steps^2,
                  pmax(0, 2 / Tp_steps - t_seq / Tp_steps^2))
  uh / sum(uh)
}

# =============================================================================
# SECTION 3 : SUMMARY AND CONVERSION HELPERS
# =============================================================================

#' Summarise a ReFH2 simulation result
#'
#' @param result  `data.table` returned by [refh2_run()].
#' @param area_km2 Catchment area \[km²\] for conversion to m³/s. If `NULL`,
#'                 outputs remain in mm/timestep.
#' @param dt_hr   Timestep \[hours\]. If `NULL`, inferred from `result`.
#'
#' @return A named list: `peak_mm`, `peak_m3s`, `volume_mm`, `volume_Mm3`,
#'   `time_to_peak_hr`.
#' @export
refh2_summary <- function(result, area_km2 = NULL, dt_hr = NULL) {
  if (is.null(dt_hr))
    dt_hr <- diff(result$time_min[1:2]) / 60

  peak_mm <- attr(result, "peak_flow_mm")
  vol_mm  <- attr(result, "flood_volume_mm")  # mm·hr
  ttp_hr  <- result$time_hr[which.max(result$Q_mm)]

  out <- list(
    peak_mm       = peak_mm,
    volume_mm_hr  = vol_mm,
    time_to_peak_hr = ttp_hr
  )

  if (!is.null(area_km2)) {
    # mm/ts * km2 -> m3/s: (mm/1000) * (km2 * 1e6) / (dt_hr * 3600)
    out$peak_m3s  <- mm_to_m3s(peak_mm, area_km2, dt_hr)
    out$volume_Mm3 <- vol_mm * area_km2 * 1e6 / (1000 * 1e6)  # million m3
  }

  out
}
